In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])

In [4]:
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension

In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [10]:
b.shape

(2, 3)

In [11]:
a.dtype

dtype('int32')

In [13]:
a.itemsize

4

In [14]:
a.size

3

In [16]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
a.shape

(2, 7)

In [18]:
a[1 , 3]

11

In [19]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
a[:, 2]

array([ 3, 10])

In [21]:
a[0, 1:]

array([2, 3, 4, 5, 6, 7])

In [24]:
a[1, 5] = 20
print(a)

a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [26]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
b[0, 1, 1]

4

In [39]:
# All 0s matrix
np.zeros((2, 3, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [40]:
# All 1s matrix
np.ones((4, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [46]:
# Any other number
np.full((2, 2), 22)

array([[22, 22],
       [22, 22]])

In [47]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [50]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.89166075, 0.32921294],
       [0.99329464, 0.48859679],
       [0.12701792, 0.56200417],
       [0.8349411 , 0.97804308]])

In [52]:
# Random Integer values 
np.random.randint(15, size=(3,3))

array([[ 1,  0, 11],
       [11,  9, 13],
       [14, 13, 13]])

In [54]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [64]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [68]:
output = np.ones((5,5))
print(output)

zer = np.zeros((3, 3))
zer[1, 1] = 9
print(zer)

output[1:4, 1:4] = zer
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [72]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


In [74]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [75]:
a + 2

array([3, 4, 5, 6])

In [76]:
a - 2

array([-1,  0,  1,  2])

In [77]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [80]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [81]:
a ** 2

array([ 1,  4,  9, 16])

In [82]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [83]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [88]:
a = np.full((2,3), 1)
a

b = np.full((3,2), 5)
b

np.matmul(a, b)

array([[15, 15],
       [15, 15]])

In [89]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [90]:
stats = np.array([ [1,2,3], [4,5,6] ])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
np.min(stats)

1

In [3]:
import numpy as np
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [7]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [10]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])